### ISSUE TITLE
Error when no override settings are provided.

### ISSUE THREAD

**Issue by Zoltu** [ivogabe/gulp-typescript#102]
`var tsProject = typescript.createProject('tsconfig.json');`

```
[16:42:12] TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Function.createProject (C:\Users\Micah\Source\Zoltu.RepoCreator.Client\node_modules\gulp-typescript\release\main.js:158:46)
    at Gulp.<anonymous> (C:\Users\Micah\Source\Zoltu.RepoCreator.Client\build\tasks\build.js:22:29)
    at module.exports (C:\Users\Micah\Source\Zoltu.RepoCreator.Client\node_modules\gulp\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\Users\Micah\Source\Zoltu.RepoCreator.Client\node_modules\gulp\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\Users\Micah\Source\Zoltu.RepoCreator.Client\node_modules\gulp\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\Users\Micah\Source\Zoltu.RepoCreator.Client\node_modules\gulp\node_modules\orchestrator\index.js:134:8)
    at C:\Users\Micah\Source\Zoltu.RepoCreator.Client\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:355:11)
````

Changing the call to this fixes it:
`var tsProject = typescript.createProject('tsconfig.json', {});`

**Comment by ivogabe** [comment]
Thanks for reporting, fixed
