### ISSUE TITLE
2.7.0: output.js:originalFileName does not exist

### ISSUE THREAD

**Issue by tensorproduct** [ivogabe/gulp-typescript#107]
Version 2.7.0 now causes our build to fail, with the following error message:

```
C:\Users\repos\node_modules\gulp-typescript\release\output.js:59
                    file.skipPush = !file.original.gulp;
                                                  ^
TypeError: Cannot read property 'gulp' of undefined
    at Output.addOrMergeFile (C:\Users\repos\node_modules\gulp-typescript\release\output.js:59:51)
    at Output.write (C:\Users\repos\node_modules\gulp-typescript\release\output.js:35:14)
    at ProjectCompiler.inputDone (C:\Users\repos\node_modules\gulp-typescript\release\compiler.js:58:33)
    at CompileStream.end (C:\Users\repos\node_modules\gulp-typescript\release\main.js:52:31)
    at DestroyableTransform.onend (C:\Users\repos\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at C:\Users\reposnode_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)
```

Compiling .ts files manually with `tsc` still works.

This seems to happen because of the following code in `output.js` resolves `originalFileName` to a path that doesn't exist.

```
var originalFileName = path.resolve(file.sourceMap.sourceRoot, file.sourceMap.sources[0]);
file.original = this.project.input.getFile(originalFileName);
file.skipPush = !file.original.gulp;
```

If my source file is located at `C:\Users\repos\src\modules\foo\foobar.ts` then `originalFileName` is assigned the value `C:\Users\repos\src\modules\foo\src\modules\foo\foobar.ts`, which does not exist. I'm pretty sure this is causing the failure that I'm seeing.

**Comment by ivogabe** [comment]
Can you post your gulpfile?

**Comment by tensorproduct** [comment]
Yep, that would help!

```
var gulp = require("gulp");
var typescript = require("gulp-typescript");

gulp.task("compile-typescript", function(cb){

    var config = {
        dest: "./build/js",
        tsOptions:{
            module: "commonjs",
            declarationFiles: true
        }
    };

    gulp.src("./src/**/*.ts")
        .pipe(typescript(config.tsOptions))
        .pipe(gulp.dest(config.dest));
});
```

**Comment by sccolbert** [comment]
I'm seeing the same failure:
```
D:\Dev\phosphorjs\phosphor\node_modules\gulp-typescript\release\output.js:59
                    file.skipPush = !file.original.gulp;
                                                  ^
TypeError: Cannot read property 'gulp' of undefined
    at Output.addOrMergeFile (D:\Dev\phosphorjs\phosphor\node_modules\gulp-types
cript\release\output.js:59:51)
    at Output.write (D:\Dev\phosphorjs\phosphor\node_modules\gulp-typescript\rel
ease\output.js:35:14)
    at ProjectCompiler.inputDone (D:\Dev\phosphorjs\phosphor\node_modules\gulp-t
ypescript\release\compiler.js:58:33)
    at CompileStream.end (D:\Dev\phosphorjs\phosphor\node_modules\gulp-typescrip
t\release\main.js:52:31)
    at DestroyableTransform.onend (D:\Dev\phosphorjs\phosphor\node_modules\gulp\
node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_st
ream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at D:\Dev\phosphorjs\phosphor\node_modules\gulp\node_modules\vinyl-fs\node_m
odules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)
```

Gulp task:
https://github.com/phosphorjs/phosphor/blob/master/gulpfile.js#L115

**Comment by ivogabe** [comment]
Strange, for me it works.. I've tested it on Mac & Windows. Which node version are you using? (`node --version`)

**Comment by sccolbert** [comment]
```
D:\Dev\phosphorjs\phosphor>node --version
v0.12.2
```

In the meantime, I rolled back to `gulp-typescript` version `2.4.2`, which works fine.

**Comment by mircolino** [comment]
I had the same problem.
Using Typescript master from microsft/typescript fixed it for me.

**Comment by derekpitt** [comment]
Same issue here

```
6059 File 'C:/projects/goodprospect2015/Source/UI/src/app.ts' is not under 'rootDir' 'C:\projects\goodprospect2015\Source\UI\node_modules\typescript\bin'. 'rootDir' is expected to contain all source files.
 
C:\projects\goodprospect2015\Source\UI\node_modules\gulp-typescript\release\output.js:59
                    file.skipPush = !file.original.gulp;
                                                  ^
TypeError: Cannot read property 'gulp' of undefined
```

does everyone else have that `rootDir` error above also?

**Comment by mikeputnam** [comment]
Like @sccolbert we were able to fix our build with 2.4.2.
```
$ nodejs --version
v0.10.38
```

**Comment by ivogabe** [comment]
I've tested it with v0.10 & 0.12, both are working for me. I also tested it with the repo of @sccolbert. Do your files have different base-paths? Eg do you use `gulp.src(['dir1/**/**.ts', 'dir2/**/**.ts'])`.

@mircolino @derekpitt @mikeputnam Can you post your project or gulpfile?

In the meantime, you can go back to the previous release, 2.6.0.

**Comment by sccolbert** [comment]
@ivogabe when did you test my repo? I update the `package.json` to hard-require `2.4.2` a couple hours ago:
https://github.com/phosphorjs/phosphor/commit/58e50d33991c8c6f44992f2bb8e3d365f611234b

**Comment by ivogabe** [comment]
I saw I tested it with 2.4.2, but now I've also tested it with 2.7.0 and it's still working... Can you replace `typings.concat(tsSources)` with `tsSources` (line 124)?

**Comment by sccolbert** [comment]
Doing a fresh checkout of my repo, using `gulp-typescript 2.7.0` setup with these commands:

```
npm install
tsd reinstall -so
```

Then run `gulp`. I get this error:
```
E:\Development\phosphorjs\test\phosphor>gulp
[14:58:04] Using gulpfile E:\Development\phosphorjs\test\phosphor\gulpfile.js
[14:58:04] Starting 'src'...
[14:58:04] Starting 'styl'...
[14:58:04] Finished 'styl' after 240 ms

E:\Development\phosphorjs\test\phosphor\node_modules\gulp-typescript\release\out
put.js:59
                    file.skipPush = !file.original.gulp;
                                                  ^
TypeError: Cannot read property 'gulp' of undefined
    at Output.addOrMergeFile (E:\Development\phosphorjs\test\phosphor\node_modul
es\gulp-typescript\release\output.js:59:51)
    at Output.write (E:\Development\phosphorjs\test\phosphor\node_modules\gulp-t
ypescript\release\output.js:35:14)
    at ProjectCompiler.inputDone (E:\Development\phosphorjs\test\phosphor\node_m
odules\gulp-typescript\release\compiler.js:58:33)
    at CompileStream.end (E:\Development\phosphorjs\test\phosphor\node_modules\g
ulp-typescript\release\main.js:52:31)
    at DestroyableTransform.onend (E:\Development\phosphorjs\test\phosphor\node_
modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-s
tream\lib\_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
    at E:\Development\phosphorjs\test\phosphor\node_modules\gulp\node_modules\vi
nyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.j
s:965:16
    at process._tickCallback (node.js:419:13)
```

Making the change you suggest, I get this error:
```
E:\Development\phosphorjs\test\phosphor>gulp
[15:00:35] Using gulpfile E:\Development\phosphorjs\test\phosphor\gulpfile.js
[15:00:35] Starting 'src'...
[15:00:35] Starting 'styl'...
[15:00:35] Finished 'styl' after 244 ms
src\shell\bootstrapper.ts(76,14): 7006 Parameter 'ex' implicitly has an 'any' ty
pe.
src\shell\bootstrapper.ts(141,33): 2304 Cannot find name 'Promise'.
src\shell\bootstrapper.ts(142,12): 2304 Cannot find name 'Promise'.
src\shell\ipluginlist.ts(26,27): 2304 Cannot find name 'Promise'.
src\shell\ipluginlist.ts(26,49): 2304 Cannot find name 'Promise'.
src\shell\pluginlist.ts(38,27): 2304 Cannot find name 'Promise'.
src\shell\pluginlist.ts(38,49): 2304 Cannot find name 'Promise'.
src\shell\pluginlist.ts(39,12): 2304 Cannot find name 'Promise'.
src\shell\pluginlist.ts(39,38): 7006 Parameter 'resolved' implicitly has an 'any
' type.
src\shell\pluginlist.ts(40,24): 7006 Parameter 'plugin' implicitly has an 'any'
type.
[15:00:36] Finished 'src' after 1.26 s
[15:00:36] Starting 'build'...
[15:00:36] Finished 'build' after 6.5 µs
[15:00:36] Starting 'dist'...
[15:00:37] Finished 'dist' after 884 ms
[15:00:37] Starting 'default'...
[15:00:37] Finished 'default' after 5.8 µs
```

And that's because the external typing definitions must be included in order to cleanly compile.

**Comment by ivogabe** [comment]
Can you retry it with the [common-base](https://github.com/ivogabe/gulp-typescript/tree/common-base) branch?

**Comment by jasongrout** [comment]
I'm seeing the same failure in my project (which has a gulp file based on @sccolbert's project).  Inserting some console.log statements around https://github.com/ivogabe/gulp-typescript/blob/master/release/output.js#L57 showed that the `file.sourceMap.sourceRoot` path was not being updated across different source files in different directories - the directory was the same as the first file in `this.files`, even if the files did come from different directories.  Thus the `originalFileName` on that line was wrong, which led to the errors above.

When I downgrade to gulp-typescript 2.6.0, everything works fine.

**Comment by jasongrout** [comment]
I just tried the common-base branch, and it seemed to work.  I inserted some console.log statements to check the originalFileName at the line I mentioned above, and it looks like it has the correct paths now.

Thanks!

**Comment by ivogabe** [comment]
Can everyone test it with v2.7.1?

**Comment by jasongrout** [comment]
Thanks.  I'll test it on Monday.

**Comment by ForNeVeR** [comment]
I am using 2.7.1 and this is still an issue for me.

**Comment by sccolbert** [comment]
Version `2.7.1` still fails for me as well.

**Comment by ivogabe** [comment]
Found it, there were two characters missing in the previous fix. Can you test it again using the master?

**Comment by sccolbert** [comment]
Just tested against `master`, it's working now. Cheers!

**Comment by ivogabe** [comment]
Nice, I've released v2.7.2 with the fix. Did this fix it for everyone?

**Comment by tensorproduct** [comment]
Yes, 2.7.2 fixes the problem for me! Thanks

**Comment by Sodentra** [comment]
I'm still seeing this issue in 2.7.3 and 2.7.2

**Comment by ivogabe** [comment]
@Sodentra can you post your project or a minimal example that can reproduce it?
