### ISSUE TITLE
Object release has no method 'on'

### ISSUE THREAD

**Issue by arolson101** [ivogabe/gulp-typescript#111]
In the readme where it says
```
gulp.task('scripts', function() {
    var tsResult = tsProject.src() // instead of gulp.src(...)
        .pipe(ts(tsProject));

    return tsResult.js.pipe('release');
});
```

Should it be this?
```
    return tsResult.js.pipe(gulp.dest('release'));
```

Because I get this error otherwise:

```
[10:35:57] TypeError: Object release has no method 'on'
    at CompileStream.Readable.pipe (_stream_readable.js:494:8)
    at Gulp.gulp.task.gulp.src.pipe.typescript.module (/Users/aolson/Developer/updraft/Gulpfile.js:19:24)
    at module.exports (/Users/aolson/Developer/updraft/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/aolson/Developer/updraft/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/aolson/Developer/updraft/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/aolson/Developer/updraft/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/lib/node_modules/gulp/bin/gulp.js:121:20
    at process._tickCallback (node.js:419:13)
    at Function.Module.runMain (module.js:499:11)
    at startup (node.js:119:16)

/Users/aolson/Developer/updraft/node_modules/gulp-typescript/release/output.js:59
                    file.skipPush = !file.original.gulp;
                                                  ^
TypeError: Cannot read property 'gulp' of undefined
    at Output.addOrMergeFile (/Users/aolson/Developer/updraft/node_modules/gulp-typescript/release/output.js:59:51)
    at Output.write (/Users/aolson/Developer/updraft/node_modules/gulp-typescript/release/output.js:35:14)
    at ProjectCompiler.inputDone (/Users/aolson/Developer/updraft/node_modules/gulp-typescript/release/compiler.js:57:33)
    at CompileStream.end (/Users/aolson/Developer/updraft/node_modules/gulp-typescript/release/main.js:52:31)
    at DestroyableTransform.onend (/Users/aolson/Developer/updraft/node_modules/gulp-typescript/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
    at /Users/aolson/Developer/updraft/node_modules/gulp-typescript/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:419:13)
```

**Comment by ivogabe** [comment]
Thanks for reporting, that's indeed a mistake. Fixed.
