### ISSUE TITLE
Resolved files outside of the gulp base path break the build

### ISSUE THREAD

**Issue by jseto** [ivogabe/gulp-typescript#112]
A weird behavior is seen in ver.2.7.2

this error is found after updating to gulp-typescript v.2.7.2
```
/home/jseto/programming-projects/web/granada-prototypes/node_modules/gulp-typescript/release/output.js:59
                    file.skipPush = !file.original.gulp;
                                                  ^
TypeError: Cannot read property 'gulp' of undefined
    at Output.addOrMergeFile (/home/jseto/programming-projects/web/granada-prototypes/node_modules/gulp-typescript/release/output.js:59:51)
    at Output.write (/home/jseto/programming-projects/web/granada-prototypes/node_modules/gulp-typescript/release/output.js:35:14)
    at ProjectCompiler.inputDone (/home/jseto/programming-projects/web/granada-prototypes/node_modules/gulp-typescript/release/compiler.js:57:33)
    at CompileStream.end (/home/jseto/programming-projects/web/granada-prototypes/node_modules/gulp-typescript/release/main.js:52:31)
    at DestroyableTransform.onend (/home/jseto/programming-projects/web/granada-prototypes/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:180:16)
    at DestroyableTransform.emit (events.js:117:20)
    at /home/jseto/programming-projects/web/granada-prototypes/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:448:13)
```

this happens with this configuration

```
var tsTest = function(){
    var tsResult = gulp.src([
		path.test.client + '**/*.ts',
	])
    .pipe( ts({
		target: 'ES5'
	}) );

    return tsResult.js.pipe( gulp.dest( path.test.outputFiles ) );
};
```

and the files in path.test.client are these https://github.com/jseto/granada-prototypes/tree/master/test

you can reproduce by cloning https://github.com/jseto/granada-prototypes
and running gulp ts:test

**Comment by rogierschouten** [comment]
I have this too since the upgrade

**Comment by rogierschouten** [comment]
The problem seems to have been introduced between v2.6.0 and v2.7.0.

**Comment by ivogabe** [comment]
There was an issue with files outside of the common base directory. I've implemented a fix in the `common-source-dir` branch. Can you test it with that branch?

**Comment by rogierschouten** [comment]
Don't have time at the moment, I downgraded to 2.6.0 for the moment. I'll let you know if I do.

**Comment by jseto** [comment]
@ivogabe The fix works and have solved my problem. Thanks!!
