### ISSUE TITLE
Regression in v2.7.3

### ISSUE THREAD

**Issue by aradzie** [ivogabe/gulp-typescript#114]
My project compilation is suddenly broken after updating from gulp-typescript 2.7.2 to 2.7.3.

```
/home/user/project/node_modules/gulp-typescript/node_modules/source-map/lib/source-map/array-set.js:83
    throw new Error('No element indexed by ' + aIdx);
          ^
Error: No element indexed by 29
    at ArraySet_at [as at] (/home/user/project/node_modules/gulp-typescript/node_modules/source-map/lib/source-map/array-set.js:83:11)
    at SourceMapConsumer_parseMappings [as _parseMappings] (/home/user/project/node_modules/gulp-typescript/node_modules/source-map/lib/source-map/source-map-consumer.js:410:44)
    at SourceMapConsumer.Object.defineProperty.get (/home/user/project/node_modules/gulp-typescript/node_modules/source-map/lib/source-map/source-map-consumer.js:73:14)
    at SourceMapConsumer_eachMapping [as eachMapping] (/home/user/project/node_modules/gulp-typescript/node_modules/source-map/lib/source-map/source-map-consumer.js:139:24)
    at Function.SourceMapGenerator_fromSourceMap (/home/user/project/node_modules/gulp-typescript/node_modules/source-map/lib/source-map/source-map-generator.js:52:26)
    at Output.applySourceMaps (/home/user/project/node_modules/gulp-typescript/release/output.js:97:54)
    at Output.addOrMergeFile (/home/user/project/node_modules/gulp-typescript/release/output.js:66:22)
    at Output.write (/home/user/project/node_modules/gulp-typescript/release/output.js:35:14)
    at ProjectCompiler.inputDone (/home/user/project/node_modules/gulp-typescript/release/compiler.js:59:33)
    at CompileStream.end (/home/user/project/node_modules/gulp-typescript/release/main.js:52:31)
```

**Comment by ivogabe** [comment]
Can you post your project or create an example that reproduces it?

**Comment by ivogabe** [comment]
Can you also retest it with the current master?

**Comment by aradzie** [comment]
The reason for error is that my `main.ts` file references another ts file that is outside of the sources dir.
So the directory layout is as follows:

```
.
├── foo.ts
├── gulpfile.js
├── package.json
└── src
    └── ts
        └── main.ts
```

and the `main.ts` file references `foo.ts`:
```
/// <reference path="../../foo.ts" />
```

**Comment by ivogabe** [comment]
Can you post your gulp file?

**Comment by aradzie** [comment]
I have posted a sample project to the first file hosting web site I have found online. Here is the link: http://s000.tinyupload.com/index.php?file_id=45372232451953110536
Download it, unzip, npm install then gulp, as usual.

**Comment by ivogabe** [comment]
This has been fixed in the master, I'll release it on npm soon.

**Comment by aradzie** [comment]
I confirm it works as expected now. Thanks for the quick fix!
