### ISSUE TITLE
unable to process empty project due to commonBasePath error

### ISSUE THREAD

**Issue by igorlino** [ivogabe/gulp-typescript#136]
In my windows installation, after updating from gulp-typescript 2.6 to 2.7.5 the project where I work is not able to an app.d.ts file (with empty contents).

```
C:\projects\app-proj\node_modules\gulp-typescript\release\input.js:121
                .reduce(getCommonBasePath);
                 ^
TypeError: Reduce of empty array with no initial value
    at Array.reduce (native)
    at FileDictionary.Object.defineProperty.get [as commonBasePath] (C:\projects\app-proj\node_modules\gulp-typescript\release\input.js:121:18)
    at FileCache.Object.defineProperty.get [as commonBasePath] (C:\projects\app-proj\node_modules\gulp-typescript\release\input.js:206:32)
    at ProjectCompiler.inputDone (C:\projects\app-proj\node_modules\gulp-typescript\release\compiler.js:41:38)
    at CompileStream.end (C:\projects\app-proj\node_modules\gulp-typescript\release\main.js:52:31)
    at DestroyableTransform.onend (C:\projects\app-proj\node_modules\gulp-sourcemaps\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at C:\projects\app-proj\node_modules\gulp-sourcemaps\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)                                                                                                                             
```

In that property commonBasePath definition the variable fileNames string contains a single file,
'C:\\projects\\app-proj\\typings\\app.d.ts'

its contents is empty, because there is no files to add there yet.  

Although unusual, It should work I think.

**Comment by igorlino** [comment]
Wow, that was amazingly fast!   +100
