### ISSUE TITLE
TypeError: Cannot read property 'referencedFiles' of undefined

### ISSUE THREAD

**Issue by rayshan** [ivogabe/gulp-typescript#179]
In general I'm confused with `isolatedCompilation` vs TypeScript compiler's `isolatedModules` option. Not sure if I'm doing this right.

TypeScript 1.5.3
gulp-typescript 2.8.0

gulpfile.js

```js
var tsProject = gp.typescript.createProject("tsconfig.json", {
    noExternalResolve: true,
    sortOutput: true
});

gulp.task("ts", function () {
    var tsResult = tsProject.src()
        .pipe(gp.sourcemaps.init())
        .pipe(gp.typescript(tsProject));

    return tsResult.js
        .pipe(gp.concat('main.js'))
        .pipe(gp.sourcemaps.write("./"))
        .pipe(gulp.dest("build/assets/scripts"));
});
```

tsconfig.json

```json
{
    "compilerOptions": {
        "module": "commonjs",
        "declaration": false,
        "isolatedModules": true,
        "target": "ES5",
        "removeComments": true
    },
    "files": [
        "typings/tsd.d.ts",
        "assets/scripts/map.ts",
        "assets/scripts/modal.ts",
        "assets/scripts/photo.ts"
    ]
}
```

Error:
```
/Users/rayshan/=Projects=/cartier/node_modules/gulp-typescript/release/output.js:187
                var references = file.original.ts.referencedFiles.map(function
                                                 ^
TypeError: Cannot read property 'referencedFiles' of undefined
    at sortedEmit (/Users/rayshan/=Projects=/cartier/node_modules/gulp-typescript/release/output.js:187:50)
    at Output.finish (/Users/rayshan/=Projects=/cartier/node_modules/gulp-typescript/release/output.js:195:17)
    at FileCompiler.inputDone (/Users/rayshan/=Projects=/cartier/node_modules/gulp-typescript/release/compiler.js:200:29)
    at CompileStream.end (/Users/rayshan/=Projects=/cartier/node_modules/gulp-typescript/release/main.js:53:31)
    at DestroyableTransform.onend (/Users/rayshan/=Projects=/cartier/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at /Users/rayshan/=Projects=/cartier/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)
```

Without `isolatedModules` in tsconfig.json, compilation does work but I get odd errors:

```
[21:26:47] Using gulpfile ~/=Projects=/cartier/gulpfile.js
[21:26:47] Starting 'ts'...
assets/scripts/map.ts(14,19): error TS2503: Cannot find namespace 'google'.
assets/scripts/map.ts(15,21): error TS2503: Cannot find namespace 'google'.
assets/scripts/map.ts(22,31): error TS2503: Cannot find namespace 'google'.
assets/scripts/map.ts(61,21): error TS2503: Cannot find namespace 'google'.
assets/scripts/map.ts(67,25): error TS2304: Cannot find name 'google'.
assets/scripts/map.ts(68,27): error TS2304: Cannot find name 'google'.
assets/scripts/modal.ts(38,26): error TS2304: Cannot find name 'Mousetrap'.
assets/scripts/modal.ts(97,9): error TS2304: Cannot find name 'Mousetrap'.
assets/scripts/photo.ts(149,9): error TS2304: Cannot find name 'Mousetrap'.
assets/scripts/photo.ts(164,9): error TS2304: Cannot find name 'Mousetrap'.
assets/scripts/photo.ts(165,9): error TS2304: Cannot find name 'Mousetrap'.
assets/scripts/photo.ts(166,9): error TS2304: Cannot find name 'Mousetrap'.
assets/scripts/photo.ts(167,9): error TS2304: Cannot find name 'Mousetrap'.
typings/tsd.d.ts(1,1): error TS6053: File '/Users/rayshan/=Projects=/cartier/typings/googlemaps/google.maps.d.ts' not found.
typings/tsd.d.ts(2,1): error TS6053: File '/Users/rayshan/=Projects=/cartier/typings/mousetrap/mousetrap.d.ts' not found.
typings/tsd.d.ts(3,1): error TS6053: File '/Users/rayshan/=Projects=/cartier/typings/jquery/jquery.d.ts' not found.
typings/tsd.d.ts(4,1): error TS6053: File '/Users/rayshan/=Projects=/cartier/typings/velocity-animate/velocity-animate.d.ts' not found.
[21:26:48] TypeScript: 17 semantic errors
[21:26:48] TypeScript: emit succeeded (with errors)
[21:26:48] Finished 'ts' after 1.17 s
```

The `d.ts` files are definitely there and the paths are correct. Perhaps a bug w/ TypeScript's compiler? Happy to file a separate bug.

**Comment by ivogabe** [comment]
I saw that isolatedCompilation in the readme is mistaken, it should be isolatedModules.

I don't think your configuration is good. Why are you using `"module": "commonjs"` and `gulp-concat`? You can't just concat commonjs files. I think isolatedModules and sortOutput don't work together, but it's a strange combination to use them both: sortOutput is useful when not using external modules and isolatedModules can only be used when using external modules. I'll add a better error message here as the current isn't helpful.

The other errors you're getting are caused by noExternalResolve: when that option is true, gulp-typescript will not try to resolve files outside of the gulp stream. In your example `typings/tsd.d.ts` is in the gulp stream but typings/googlemaps/google.maps.d.ts` not. The easiest fix would be to remove noExternalResolve.

**Comment by rayshan** [comment]
Good points. I'm not actually using modules. I only added `"module": "commonjs"` because TypeScript compiler said `"isolatedModules"` doesn't work w/o it, which makes sense. I removed both of those, `noExternalResolve` and `sortOutput`, as output appears to be sorted without this option, based on the order defined in `tsconfig.json`. Still using `gulp-concat`. Things are working well now. Thanks.
