### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jedmao** [ivogabe/gulp-typescript#181]
I'm using tsc, version 1.5.3:

```
/.../GitHub/postcss (master *)
22:13 $tsc -v
message TS6029: Version 1.5.3
```
With the following `tsconfig.json`:

```json
{
    "compilerOptions": {
        "target": "es6",
        "declaration": true,
        "newLine": "LF",
        "outDir": "build",
        "rootDir": "."
    },
    "files": [
      "lib/foo.ts",
      "test/foo.ts"
    ]
}

```

If I just run the `tsc` command, everything builds fine into the `build/` folder; however, if I run my gulp task:

```js
gulp.task('build', () => {
    let ts = require('gulp-typescript');
    let project = ts.createProject('tsconfig.json');
    let tsCompilerOptions = require('./tsconfig').compilerOptions;
    return project.src().pipe(ts(project)).js.pipe(tsCompilerOptions.outDir);
});
```

I get the following error:

```
/.../GitHub/postcss (master *)
22:13 $gulp build
[22:13:48] Requiring external module babel-core/register
[22:13:48] Using gulpfile Z:\Documents\GitHub\postcss\gulpfile.babel.js
[22:13:48] Starting 'build'...
[22:13:48] 'build' errored after 225 ms
[22:13:48] TypeError: undefined is not a function
    at CompileStream.Readable.pipe (_stream_readable.js:495:8)
    at Gulp.<anonymous> (Z:/Documents/GitHub/postcss/gulpfile.babel.js:18:47)
    at module.exports (Z:\Documents\GitHub\postcss\node_modules\gulp\node_module
s\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (Z:\Documents\GitHub\postcss\node_modules\gulp
\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (Z:\Documents\GitHub\postcss\node_modules\gulp
\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (Z:\Documents\GitHub\postcss\node_modules\gulp\no
de_modules\orchestrator\index.js:134:8)
    at c:\Users\jedma\AppData\Roaming\npm\node_modules\gulp\bin\gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
```

If I, instead, pipe-out the `d.ts` files, everything works fine.

I'm also confused, because I have essentially the same setup at [postcss-triangle](https://github.com/jedmao/postcss-triangle), which works perfectly well.

Any ideas? Or have you seen this before?

I even tried creating a `foo.ts` file like this:

```ts
export default class Foo {
    bar: string;
}
```

And compiling only that file and it doesn't work w/ gulp-typescript for some reason.

**Comment by ivogabe** [comment]
Looks like you should replace `.pipe(tsCompilerOptions.outDir);` with `.pipe(gulp.dest(tsCompilerOptions.outDir));`. I must say that I've made that mistake too, more than once.

**Comment by jedmao** [comment]
OMG, how embarrassing! >_<
