### ISSUE TITLE
Can't generate d.ts files: errors out on `tsResult.dts.pipe` call

### ISSUE THREAD

**Issue by matthewjh** [ivogabe/gulp-typescript#183]
Hi,

My `tsconfig.json`:

````
{
  "compilerOptions": {
    "target": "ES5",
    "module": "commonjs",
    "rootDir": ".",
    "outDir": "built",
    "noEmitOnError": true,
    "experimentalDecorators": true,
    "declaration": true
  },
  "filesGlob": [
    "src/**/*.ts",
    "test/**/*.ts",
    "definitions/**/*.d.ts"
  ]
}
````

and my gulp task:

````
gulp.task('build', function (done) {
  var tsconfig = require("./tsconfig.json");
  var filesGlob = tsconfig.filesGlob;

  tsconfig.compilerOptions.typescript = require('typescript');
  
  var tsResult = gulp.src(filesGlob)
    .pipe(ts(tsconfig.compilerOptions));
    
  return merge([
    tsResult.dts.pipe(tsconfig.compilerOptions.outDir),
    tsResult.js.pipe(tsconfig.compilerOptions.outDir)
  ]);
});
````

`require('typescript')` refers to v1.6.0-dev

and the error:
````
✗ gulp build
[21:21:51] Using gulpfile ~/Documents/Personal/Syringe/gulpfile.js
[21:21:51] Starting 'build'...
[21:21:51] 'build' errored after 11 ms
[21:21:51] TypeError: undefined is not a function
    at CompileOutputStream.Readable.pipe (_stream_readable.js:495:8)
    at Gulp.<anonymous> (/Users/mattewhill/Documents/Personal/Syringe/gulpfile.js:46:18)
    at module.exports (/Users/mattewhill/Documents/Personal/Syringe/node_modules/gulp/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/Users/mattewhill/Documents/Personal/Syringe/node_modules/gulp/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/Users/mattewhill/Documents/Personal/Syringe/node_modules/gulp/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/Users/mattewhill/Documents/Personal/Syringe/node_modules/gulp/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
`````

Where `gulpfile.js:46` is the line in the gulp task calling `tsResult.dts.pipe`

**Comment by ivogabe** [comment]
Looks like you missed `gulp.dest(...)` (in the return statement).

**Comment by matthewjh** [comment]
Ahh!! Thanks @ivogabe, that fixed it.
