### ISSUE TITLE
2.8.1: isolatedModules: true always causes a javascript error when running gulp-typescript

### ISSUE THREAD

**Issue by maximumduncan** [ivogabe/gulp-typescript#185]
The gulp task:

```js
gulp.task('example', function() {
	return gulp.src([])
		.pipe(ts({isolatedModules: true}))
		.js
		.pipe(gulp.dest('dist'));
});
```

will always fail with the following javascript error:

```
TypeError: Cannot read property 'syntaxErrors' of undefined
    at Object.defaultFinishHandler [as finish] (/myproject/node_modules/gulp-typescript/releasereporter.js:21:27)
    at Output.finish (/myproject/node_modules/gulp-typescript/release/output.js:200:35)
    at FileCompiler.inputDone (/myproject/node_modules/gulp-typescript/release/compiler.js:200:9)
    at CompileStream.end (/myproject/node_modules/gulp-typescript/release/main.js:53:31)
    at DestroyableTransform.onend (/myproject/node_modules/gulp/node_modules/vinyl-fs/node_modues/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at DestroyableTransform.g (events.js:199:16)
    at DestroyableTransform.emit (events.js:129:20)
    at /myproject/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/redable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:355:11)
    at Function.Module.runMain (module.js:503:11)
    at startup (node.js:129:16)
    at node.js:814:3
```

Obviously even if it worked this example achieves nothing; I stripped away a lot of the configuration to illustrate the error as simply as possible.

I am using gulp-typescript `2.8.1`.

**Comment by ivogabe** [comment]
Thanks for reporting!
