### ISSUE TITLE
Filter not working

### ISSUE THREAD

**Issue by n2westman** [ivogabe/gulp-typescript#213]
```
gulp.task('typescript', function () {
	var tsStream = gulp.src(sourceFiles)
		.pipe(ts(tsProject, {referencedFrom: [outFiles[0]]}))
		.js
		.pipe(concat(outFiles[0].replace(/\.ts$/,'.js')));

	return tsStream.pipe(gulp.dest('.'));
});
```
works, while

```
gulp.task('typescript', function () {
	var tsStream = gulp.src(sourceFiles)
		.pipe(ts(tsProject))
		.pipe(ts.filter({referencedFrom: [outFiles[0]]}))
		.pipe(concat(outFiles[0].replace(/\.ts$/,'.js')));

	return tsStream.pipe(gulp.dest('.'));
});
```
Does not.

Error below.

```
        if (filters.referencedFrom !== undefined) {
                   ^
TypeError: Cannot read property 'referencedFrom' of undefined
    at new Filter (/Users/nickwestman/Documents/ReachClient/Web/node_modules/gulp-typescript/release/filter.js:10:20)
    at DestroyableTransform._transform (/Users/nickwestman/Documents/ReachClient/Web/node_modules/gulp-typescript/release/main.js:236:29)
    at DestroyableTransform.Transform._read (/Users/nickwestman/Documents/ReachClient/Web/node_modules/readable-stream/lib/_stream_transform.js:172:10)
    at DestroyableTransform.Transform._write (/Users/nickwestman/Documents/ReachClient/Web/node_modules/readable-stream/lib/_stream_transform.js:160:12)
    at doWrite (/Users/nickwestman/Documents/ReachClient/Web/node_modules/readable-stream/lib/_stream_writable.js:326:12)
    at writeOrBuffer (/Users/nickwestman/Documents/ReachClient/Web/node_modules/readable-stream/lib/_stream_writable.js:312:5)
    at DestroyableTransform.Writable.write (/Users/nickwestman/Documents/ReachClient/Web/node_modules/readable-stream/lib/_stream_writable.js:239:11)
    at CompileStream.ondata (_stream_readable.js:540:20)
    at CompileStream.emit (events.js:107:17)
    at readableAddChunk (_stream_readable.js:163:16)
```

**Comment by ivogabe** [comment]
You should pass the project to `ts.filter` too:
```javascript
.pipe(ts.filter(tsProject, { referencedFrom: [outFiles[0]] }))
```
I noticed the readme is wrong about this. I'll update that.
