### ISSUE TITLE
file glob error with tsconfig.json file

### ISSUE THREAD

**Issue by themauveavenger** [ivogabe/gulp-typescript#221]
Hello! Having a problem getting my build task to work. I have the following tsconfig file: 
```javascript
{
  "compilerOptions" : {
    "module": "commonjs",
    "target": "es5"
  },
  "files" : [
    "src/index.ts",
    "typings/tsd.d.ts",
    "node_modules/node_models/node_models.d.ts",
    "src/lib/corinator/Corinator.ts",
    "src/lib/dbnator/Dbnator.ts",
    "src/lib/helper/helpers.ts",
    "src/lib/rule/rules.ts",
    "src/config.ts",
    "src/routes/RuleValidatorRoutes.ts"
  ]
}
```

With the following build task and setup: 
```javascript
// setup typescript project
var tsProject = ts.createProject('tsconfig.json',
    {
      sortOutput: true,
      typescript: require('typescript')
    });

// compile typescript to javascript
gulp.task('typescripts', function () {

  return tsProject.src()
      .pipe(ts(tsProject))
      .pipe(gulp.dest('src'));

});
```

Running ```gulp typescripts``` produces the following error: 
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: File not found with singular glob
    at Glob.<anonymous> (/Users/jpetersen/IdeaProjects/node_validator/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/index.js:34:30)
    at Glob.emit (events.js:95:17)
    at Glob._finish (/Users/jpetersen/IdeaProjects/node_validator/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:172:8)
    at done (/Users/jpetersen/IdeaProjects/node_validator/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:159:12)
    at Glob._processSimple2 (/Users/jpetersen/IdeaProjects/node_validator/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:652:12)
    at /Users/jpetersen/IdeaProjects/node_validator/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:640:10
    at Glob._stat2 (/Users/jpetersen/IdeaProjects/node_validator/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:736:12)
    at lstatcb_ (/Users/jpetersen/IdeaProjects/node_validator/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/glob.js:728:12)
    at RES (/Users/jpetersen/IdeaProjects/node_validator/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/inflight/inflight.js:23:14)
    at f (/Users/jpetersen/IdeaProjects/node_validator/node_modules/gulp-typescript/node_modules/vinyl-fs/node_modules/glob-stream/node_modules/glob/node_modules/once/once.js:17:25)
```

Some other info:
node.js version: 0.10.40
typescript version I'm requiring: 1.5.3
gulp-typescript version: 2.9.2
globally installed typescript version: 1.5.3
globally installed gulp version: 3.9.0

Anybody have any ideas as to what I'm doing wrong here?

**Comment by ivogabe** [comment]
It looks like one of the files in your tsconfig file cannot be found. Can you check whether these files all exist?

**Comment by themauveavenger** [comment]
@ivogabe Thank you. ```"src/config.ts"``` had a folder missing from the path. Works now.

On that note, is there a way to get a more specific error message if something like that happens to me again?

**Comment by ivogabe** [comment]
I'll investigate that, as you should indeed get a better error in such case. The glob error from glob-stream probably shadows the usable error.

**Comment by jeffbcross** [comment]
Including the filename would be great! Someone ran into this issue on angular/universal https://github.com/angular/universal/issues/122
