### ISSUE TITLE
TypeError: Cannot read property 'gulp' of undefined

### ISSUE THREAD

**Issue by mizunashi-mana** [ivogabe/gulp-typescript#398]
Node.js reported this error on my Windows 10.
I uploaded target project to https://github.com/mizunashi-mana/test-gulp-ts/tree/gulp-typescript-issue-398.

Is this a known bug and a general bug or my miss?

**Expected behavior:**

```
$ npm i
$ npm run build
semantic errors reported, but no program errors
```

**Actual behavior:**

```bash
$ npm i
$ npm run build

> gulp-ts-test@1.0.0 build ...\gulp-ts-test
> gulp build

[16:54:01] Requiring external module coffee-script/register
[16:54:02] Using gulpfile ~\gulp-ts-test\gulpfile.coffee
[16:54:02] Starting 'build'...
src\illegal.ts(17,7): error TS1005: ',' expected.
src\illegal.ts(18,7): error TS1005: ')' expected.
src\illegal.ts(8,18): error TS4055: Return type of public method from exported class has or is using private name 'util'.
src\illegal.ts(21,28): error TS4055: Return type of public method from exported class has or is using private name 'util'.
...\gulp-ts-test\node_modules\gulp-typescript\release\output.js:159
            base = path.resolve(file.original.gulp.cwd, this.project.options.outDir) + '/';
                                             ^

TypeError: Cannot read property 'gulp' of undefined
  at Output.emit (...\gulp-ts-test\node_modules\gulp-typescript\release\output.js:159:46)
  at sortedEmit_1 (...\gulp-ts-test\node_modules\gulp-typescript\release\output.js:205:23)
  at Output.finish (...\gulp-ts-test\node_modules\gulp-typescript\release\output.js:209:17)
  at ProjectCompiler.inputDone (...\gulp-ts-test\node_modules\gulp-typescript\release\compiler.js:81:29)
  at CompileStream.end (...\gulp-ts-test\node_modules\gulp-typescript\release\main.js:54:31)
  at DestroyableTransform.onend (...\gulp-ts-test\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:523:10)
  at DestroyableTransform.g (events.js:260:16)
  at emitNone (events.js:72:20)
  at DestroyableTransform.emit (events.js:166:7)
  at ...\gulp-ts-test\node_modules\gulp\node_modules\vinyl-fs\node_modules\through2\node_modules\readable-stream\lib\_stream_readable.js:965:16
  at nextTickCallbackWith0Args (node.js:420:9)
  at process._tickCallback (node.js:349:13)
```

However, this is not caused by semantic errors simply, because that one is correct:

```bash
$ npm i
$ npm run build:correct

> gulp-ts-test@1.0.0 build:correct ...\gulp-ts-test
> gulp build:correct

[17:15:23] Requiring external module coffee-script/register
[17:15:23] Using gulpfile ~\gulp-ts-test\gulpfile.coffee
[17:15:23] Starting 'build:correct'...
src\illegal-but-correctgts.ts(1,22): error TS7006: Parameter 'e' implicitly has an 'any' type.
[17:15:24] TypeScript: 1 semantic error
[17:15:24] TypeScript: emit succeeded (with errors)
[17:15:24] Finished 'build:correct' after 934 ms

````

**Your gulpfile:**

https://github.com/mizunashi-mana/test-gulp-ts/blob/gulp-typescript-issue-398/gulpfile.coffee

**My PC Status:**

* Windows 10
* node: v4.4.3
* npm: v2.15.1

```bash
$ npm ls --depth 0
gulp-ts-test@1.0.0 ~/gulp-ts-test
├── coffee-script@1.10.0
├── gulp@3.9.1
├── gulp-typescript@2.13.6
├── merge2@1.0.2
└── typescript@1.8.10
```

**Comment by ivogabe** [comment]
Can you upgrade to TypeScript 2.0? If so, you could give gulp-typescript 3.0 a try; the logic that produces your error has been completely revised. Let me know whether that works.

**Comment by mizunashi-mana** [comment]
@ivogabe gulp-typescript 3.0 with typescript 2.0 works great for me.
Thanks for wonderful updates!
