### ISSUE TITLE
TypeError: tsProject is not a function

### ISSUE THREAD

**Issue by rehmsen** [ivogabe/gulp-typescript#418]
**Expected behavior:**

gulp-typescript builds my project accordings to tsconfig.json.

**Actual behavior:**

gulp-typescript crashes with: 

```
TypeError: tsProject is not a function
    at Gulp.<anonymous> (/home/me/myproject/gulp/client.js:50:15)
    at module.exports (/home/me/myproject/node_modules/orchestrator/lib/runTask.js:34:7)
    at Gulp.Orchestrator._runTask (/home/me/myproject/node_modules/orchestrator/index.js:273:3)
    at Gulp.Orchestrator._runStep (/home/me/myproject/node_modules/orchestrator/index.js:214:10)
    at Gulp.Orchestrator.start (/home/me/myproject/node_modules/orchestrator/index.js:134:8)
    at /usr/local/lib/node_modules/gulp/bin/gulp.js:129:20
    at nextTickCallbackWith0Args (node.js:419:9)
    at process._tickCallback (node.js:348:13)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
 ```

**Your gulpfile:**

```javascript
var tsProject = ts.createProject('tsconfig.json');
gulp.task('client:build:ts', [], () => { 
    var tsResult = tsProject.src() // instead of gulp.src(...)
        .pipe(tsProject());

    return tsResult.js.pipe(gulp.dest('release'));
});
```

**tsconfig.json**

```json
{
    "compilerOptions": {
        "target": "es5",
        "module": "commonjs",
        "noImplicitAny": true
    },
    "files": [
        "src/client/app/app.ts",
    ]
}
```

I copied the exact example code from `readme.md`. My deps are all up to date. My project builds fine when I do not use `ts.createProject` but copy the compile options into the `ts({})` call.

**Comment by ivogabe** [comment]
It looks like you're using version 2.x of gulp-typescript. In version 2, `.pipe(tsProject())` was not supported. Version 3 introduces this, and deprecates the old `.pipe(ts(tsProject))`. Can you check which version of gulp-typescript you're using?

**Comment by rehmsen** [comment]
Thanks for the quick response. My package.json had the 3.x version of gulp-typescript, but somehow the update was not installed. My bad, sorry for the noise.
