### ISSUE TITLE
Use in Yeoman generator (stream closed when writing JS files)

### ISSUE THREAD

**Issue by mattdsteele** [ivogabe/gulp-typescript#531]
Related, my use case is described here: https://github.com/yeoman/generator/issues/1030

I'm looking to use this with Yeoman, which supports Gulp plugins through vinyl transform streams: http://yeoman.io/authoring/file-system.html

My usage:

```javascript
        const filter = require('gulp-filter');
        const ts = require('gulp-typescript');
        const tsFilter = filter(['**/*.ts'], { restore: true });
        this.registerTransformStream(tsFilter);
        this.registerTransformStream(ts({
          noEmitOnError: false,
          target: 'es2015',
          module: 'es2015',
          allowJs: true
        }));
        this.registerTransformStream(tsFilter.restore);
```

Fails with:

```
   create src\index.js
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: stream.push() after EOF
    at readableAddChunk (_stream_readable.js:156:17)
    at CompileOutputStream.Readable.push (_stream_readable.js:134:10)
    at Output.writeJs (generator-test\node_modules\gulp-typescript\release\output.js:25:23)
    at ProjectCompiler.emitFile (generator-test\node_modules\gulp-typescript\release\compiler.js:135:33)
    at ProjectCompiler.inputDone (generator-test\node_modules\gulp-typescript\release\compiler.js:76:22)
    at CompileStream.end (generator-test\node_modules\gulp-typescript\release\project.js:136:31)
    at onend (generator-test\node_modules\readable-stream\lib\_stream_readable.js:498:10)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

I think this is because the stream that gulp-typescript is trying to write to has already been closed. I saw  https://github.com/ivogabe/gulp-typescript/issues/433, but using `ts.createProject()` didn't help.

Any thoughts on what could be done here? Is there a way to make `gulp-typescript` not wait until the stream's `end` before it begins to emit files?

**Comment by mattdsteele** [comment]
Gonna close this - I ended up writing a naive vinyl stream that does what I need. Here's the code for posterity.

```javascript
import through from 'through2';
import gutil from 'gulp-util';
import * as ts from 'typescript';

export default (options) => {
  return through.obj(function (file, enc, cb) {
    if (file.isNull()) {
      cb(null, file);
      return;
    }

    if (file.isStream()) {
      cb(new gutil.PluginError('gulp-tsc', 'No streams'));
      return;
    }

    try {
      const x = ts.transpileModule(file.contents.toString(), {
        compilerOptions: {
          noEmitOnError: false,
          target: 'es2015',
          module: 'es2015',
          allowJs: true
        }
      });
      file.contents = new Buffer(x.outputText);
      file.path = gutil.replaceExtension(file.path, '.js');
      cb(null, file);
    } catch (e) {
      this.emit('error', new gutil.PluginError('gulp-tsc', e));
    }
  });
};
```
