### ISSUE TITLE
target not getting passed through?

### ISSUE THREAD

**Issue by alanouri** [ivogabe/gulp-typescript#57]
Hey,

I just grabbed the latest gulp-typescript with TS 1.4.1 and I'm seeing an issue where the TS compiler is blowing up and it's related to the script target not being correct.

Exception:

```
C:\src\MYPROJECT\gulp-typescript\node_modules\typescript\bin\typescriptServices.js:1138
                throw new Error("Debug Failure. False expression: " + (message
                      ^
Error: Debug Failure. False expression: Invalid ScriptTarget. We should emit as ES6 or above
    at Object.assert (C:\src\MYPROJECT\gulp-typescript\node_modules\typescript\bin\typescriptServices.js:1138:23)
    at emitNode (C:\src\MYPROJECT\gulp-typescript\node_modules\typescript\bin\typescriptServices.js:10698:30)
    at emitNodeWithMap (C:\src\MYPROJECT\gulp-typescript\node_modules\typescript\bin\typescriptServices.js:9104:29)
    at emitMultiLineList (C:\src\MYPROJECT\gulp-typescript\node_modules\typescript\bin\typescriptServices.js:9172:25)
    at emitObjectLiteral (C:\src\MYPROJECT\gulp-typescript\node_modules\typescript\bin\typescriptServices.js:9391:21)
    at emitNode (C:\src\MYPROJECT\gulp-typescript\node_modules\typescript\bin\typescriptServices.js:10592:32)
    at emitNodeWithMap (C:\src\MYPROJECT\gulp-typescript\node_modules\typescript\bin\typescriptServices.js:9104:29)
    at emitBinaryExpression (C:\src\MYPROJECT\gulp-typescript\node_modules\typescript\bin\typescriptServices.js:9576:17)
    at emitNode (C:\src\MYPROJECT\gulp-typescript\node_modules\typescript\bin\typescriptServices.js:10626:32)
    at emitNodeWithMap (C:\src\MYPROJECT\gulp-typescript\node_modules\typescript\bin\typescriptServices.js:9104:29)
```

The asserting code, typescriptServices.js:10698:30, is an ES6 codepath, judging from the comments.

So I added a console.log(compilerOptions) above the asserting line:
```javascript
{ sourceRoot: 'C:\\MYPROJECT',
  declaration: true,
  sourceMap: true }
```
That's despite the fact that my project is defined with target:'ES5'.

Sounds like the compiler options aren't making it down to this code in typescriptServices.js.

Any ideas?

**Comment by mehdi-cit** [comment]
Hej Alanouri!
We had a similar issue. Actually not sure it's that similar, but it might help. 
A colleague of mine figured it out. In the package.json we were asking for the latest version of "gulp-typescript": "^2.3.0", 
The latest version of it is not working and causing that error. Se switched to get exactly the version that we need ( not necessarily the latest) and it started working again.
the line below works.
"gulp-typescript": "2.3.0",

**Comment by ivogabe** [comment]
Are you sure you've added a target to your gulp file? I did some testing, and found out there is a bug in 2.4.0 when you don't pass a target. I've pushed a commit to the master, can you test it with the current master from github?

**Comment by ivogabe** [comment]
Logged an issue about this at Microsoft/TypeScript#1758
