### ISSUE TITLE
TypeError: Cannot read property 'file' of undefined

### ISSUE THREAD

**Issue by viT-1** [ivogabe/gulp-typescript#623]
**Expected behavior:**
Gulp task is completed

**Actual behavior:**
Gulp task throws error
TypeError: Cannot read property 'file' of undefined
    at Output.getError (C:\Projects\systemjs-ts-es6\node_modules\gulp-typescript\release\output.js:138:29)
    at Output.diagnostic (C:\Projects\systemjs-ts-es6\node_modules\gulp-typescript\release\output.js:143:25)
    at ProjectCompiler.emit (C:\Projects\systemjs-ts-es6\node_modules\gulp-typescript\release\compiler.js:129:33)
    at ProjectCompiler.inputDone (C:\Projects\systemjs-ts-es6\node_modules\gulp-typescript\release\compiler.js:80:18)
    at CompileStream.end (C:\Projects\systemjs-ts-es6\node_modules\gulp-typescript\release\project.js:122:31)
    at DestroyableTransform.onend (C:\Projects\systemjs-ts-es6\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:286:20)
    at DestroyableTransform.emit (events.js:203:15)
    at DestroyableTransform.EventEmitter.emit (domain.js:466:23)
    at endReadableNT (C:\Projects\systemjs-ts-es6\node_modules\readable-stream\lib\_stream_readable.js:1010:12)

**Your gulpfile.esm.js:**
```javascript
import tts from 'ttypescript';
import typescript from 'gulp-typescript';
import {
	src,
	dest,
	task,
	parallel,
} from 'gulp';

task('deploy.dev',
	() => {
		// Transpiling for browser tsconfig
		const tsApp = typescript.createProject(
			'./src/tsconfig.dev.json',
			{ typescript: tts },
		);

		const tsResult = tsApp.src()
			.pipe(tsApp()).js;

		return tsResult
			.pipe(uglifyES())
			.pipe(dest(
				// deploy dev files
				tsApp.config.compilerOptions.outDir,
			));
	});

```

**Comment by viT-1** [comment]
Tested same tsconfig with npm script `ttsc --project ./tsconfig.json` it's ok, but gulp-typescript configuration is not.

**Comment by ivogabe** [comment]
Fixed in #627

**Comment by viT-1** [comment]
@ivogabe Last released version in npmjs is 5.0.1
When this fix will be released?

**Comment by ivogabe** [comment]
I plan to fix some other problems as well. I hope to release it this week

**Comment by ivogabe** [comment]
Published as 6.0.0-alpha.1.

**Comment by viT-1** [comment]
No, 6.0 it's not fixed for me =(
```
TypeError: Cannot read property 'file' of undefined
    at Output.getError (xxx\node_modules\gulp-typescript\release\output.js:139:29)
    at Output.diagnostic (xxx\node_modules\gulp-typescript\release\output.js:144:25)
    at ProjectCompiler.emit (xxx\node_modules\gulp-typescript\release\compiler.js:131:33)
    at ProjectCompiler.inputDone (xxx\node_modules\gulp-typescript\release\compiler.js:80:18)
    at CompileStream.end (xxx\node_modules\gulp-typescript\release\project.js:125:31)
    at DestroyableTransform.onend (xxx\node_modules\readable-stream\lib\_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:286:20)
    at DestroyableTransform.emit (events.js:203:15)
    at DestroyableTransform.EventEmitter.emit (domain.js:466:23)
    at endReadableNT (xxx\node_modules\readable-stream\lib\_stream_readable.js:1010:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by ivogabe** [comment]
Sorry, you were having a different issue as what I thought. Can you share a TypeScript file on which you see this error? That would make it easier for me to debug this.

**Comment by viT-1** [comment]
@ivogabe : Sorry, i'm checking your library on [small project](https://github.com/viT-1/systemjs-ts-es6-vue/commit/425813ab25d98cffa10c64d3936979febd9987ce) & everything is working, thanks!

**Comment by ivogabe** [comment]
Great, that's good news :)
