### ISSUE TITLE
Change in Typescript 3.6 API causes TypeError when using incremental

### ISSUE THREAD

**Issue by daradermody** [ivogabe/gulp-typescript#626]
**Expected behavior:**
All Typescript files in project successfully compiled

**Actual behavior:**
Crashes with the following error:
```
[16:15:44] TypeError: Cannot read property 'length' of undefined
    at Object.emit [as writeFile] (/home/dara/git/web-services/node_modules/gulp-typescript/release/compiler.js:82:33)
    at Object.writeFile (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:12098:14)
    at emitBuildInfo (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:86238:16)
    at emitSourceFileOrBundle (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:86205:13)
    at forEachEmittedFile (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:85999:28)
    at Object.emitFiles (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:86184:9)
    at emitWorker (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:92134:33)
    at /home/dara/git/web-services/node_modules/typescript/lib/typescript.js:92095:66
    at runWithCancellationToken (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:92185:24)
    at Object.emit (/home/dara/git/web-services/node_modules/typescript/lib/typescript.js:92095:20)
```
**Your gulpfile:**
```js
function compile() {
  const tsProject = ts.createProject('tsconfig.json');
  return tsProject.src()
    .pipe(tsProject())
    .pipe(dest('dist'));
}

exports.compile = compile;
```

**tsconfig.json**
```json
{
  "compilerOptions": {
    "rootDir": ".",
    "outDir": "dist",
    "module": "commonjs",
    "strict": true,
    "sourceMap": true,
    "incremental": true,
    "lib": ["esnext"],
    "target": "esnext",
    "noImplicitAny": false,
    "esModuleInterop": true
  },
  "include": [
    "src/**/*"
  ],
  "exclude": []
}
```
**My analysis**
With Typescript 3.6, the [write file callback](https://github.com/ivogabe/gulp-typescript/blob/master/lib/compiler.ts#L132L142) gets called not just with the js files emitted by the Typescript compiler, but also with the `tsconfig.tsbuildinfo` file, which has no source files so the `sourceFiles` parameter is `undefined`.

This only happens when `incremental` is set to true and doesn't happen in Typescript 3.5 because the `tsconfig.tsbuildinfo` was not passed to the callback.

This is likely an intentional change in Typescript, as the `tsc` command emits a `tsconfig.tsbuildinfo` file, but until now, it was not given to the write callback.

**Comment by judemanutd** [comment]
+1

**Comment by rozbo** [comment]
+1

**Comment by neildom** [comment]
+1

**Comment by judemanutd** [comment]
A temporary workaround as suggested in https://github.com/ivogabe/gulp-typescript/issues/499#issuecomment-538285301 is to set `"incremental": false` in your `tsconfig.json` file.

**Comment by SanderDeWaal1992** [comment]
Why is this issue closed? It is still there right? 

The workaround above is not really a solution (though I'm happy there is a workaround for now).

I popped in this issue using Typescript 3.7.3.
